---
- hosts: packages
  any_errors_fatal: false # don't bomb out the entire playbook if one host (i.e. package) fails
  gather_facts: no
  serial: 1
  vars:
    mock_build_repo: .build/build_repo
    mock_srpm_repo: .build/srpm_repo
  roles:
    - git-annex-setup
    #- ensure-package
  tasks:
    - include: tasks/setup_sources.yml

    - name: 'Make SRPM repo'
      file:
        state: directory
        path: "{{ mock_srpm_repo }}"

    - name: 'Remove old SRPM'
      file:
        state: absent
        path: "{{ mock_srpm_repo }}/{{ inventory_hostname }}-*.srpm"

    - name: 'Build srpm'
      shell: "tito build --srpm --dist=.el7 --output ../../{{ mock_srpm_repo }} --rpmbuild-options='--define \"scl_prefix tfm-ror51-\"'"
      args:
        chdir: "packages/{{ inventory_hostname }}"

- hosts: localhost
  gather_facts: no
  vars:
    mock_build_repo: .build/build_repo
    mock_srpm_repo: .build/srpm_repo
  tasks:
    - name: "Run mockchain"
      shell: "mockchain -r mock/el7.cfg --recurse -l {{ mock_build_repo }} {{ mock_srpm_repo }}/*"
      register: output

    - debug:
        msg: "{{ output.stdout }}"
