- hosts: packages
  any_errors_fatal: false # don't bomb out the entire playbook if one host (i.e. package) fails
  gather_facts: no
  serial: 1
  roles:
    - git-annex-setup
    - ensure-package

- hosts: packages
  any_errors_fatal: false # don't bomb out the entire playbook if one host (i.e. package) fails
  gather_facts: no
  tasks:
    - name: 'Get latest package info from copr'
      command: "copr-cli get-package @theforeman/tfm-ror51 --name {{ inventory_hostname }} --with-latest-build"
      register: copr_package_info
      ignore_errors: true

    - name: 'Get latest package info from git'
      command: "rpmspec --query --undefine=dist --queryformat=%{version}-%{release} --srpm packages/{{ inventory_hostname }}/{{ inventory_hostname }}.spec"
      register: git_package_info

    - set_fact:
        git_package_version: "{{ git_package_info.stdout }}"

    - set_fact:
        copr_package_info: "{{ copr_package_info.stdout | from_json }}"
      when: copr_package_info | success

    - set_fact:
        copr_package_version: "{{ copr_package_info['latest_build']['pkg_version'] }}"
      when: copr_package_info | success

    - set_fact:
        copr_package_version: ""
      when: copr_package_info | failed

    - debug:
        msg: "Git version:  {{ git_package_version }} \nCopr version: {{ copr_package_version }}"

    - block:
        - include_tasks: tasks/setup_sources.yml

        - include_tasks: tasks/tito_release.yml

        - include_tasks: tasks/build_wait_and_download.yml
      when: "git_package_version not in copr_package_version"
