---
- hosts: packages
  any_errors_fatal: false # don't bomb out the entire playbook if one host (i.e. package) fails
  gather_facts: no
  serial: 1
  roles:
    - git-annex-setup
    - ensure-package

- hosts: packages
  any_errors_fatal: false # don't bomb out the entire playbook if one host (i.e. package) fails
  gather_facts: no
  tasks:
    - include: tasks/setup_sources.yml

    - set_fact:
        tito_releasers: "{{ releasers | join(' ') | replace('nightly', 'scratch') }}"
      tags:
        - always

    - include: tasks/tito_release.yml

    - include: tasks/build_wait_and_download.yml
